### ISSUE TITLE
Paper displays blank on recent Chrome

### ISSUE THREAD

**Issue by mikesamuel** [fnogatz/paper-now-chrjs#2]
https://fnogatz.github.io/paper-now-chrjs/ shows blank and has a variety of mixed content warnings and notifications about HTML imports being deprecated in the side bar.

**Comment by mikesamuel** [comment]
![Screenshot from 2020-10-14 11-23-15](https://user-images.githubusercontent.com/368886/96010571-ee491f80-0e0f-11eb-906f-ef02aef38f1e.png)

**Comment by fnogatz** [comment]
Thanks for reporting! Resolved via 0e49d7e37cecbc9547ec48ee0e5fc752b148d073.
